# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Fry-Shell
version:      0.09
version_from: lib/Fry/Shell.pm
installdirs:  site
requires:
    Class::Data::Global:           0.01
    Term::ReadLine:                1.01

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
